"""From a fund's policy text to the formula sheet: every rule as mathematics, checked against the region.

    .venv/bin/python scripts/mandate_formula_sheet.py                 # fictional example, offline
    .venv/bin/python scripts/mandate_formula_sheet.py --live          # let Claude read the text (one API call)

Steps: (1) the policy text becomes a rule spec (the hand-written reference spec, or Claude
with --live); (2) every rule is checked against the text: its quote must be there and its
numbers must be in the quote; (3) the region's own requirements are added and compared
with the fund's; (4) the formula sheet is written: results/mandate_formula_sheet.md.

The example mandate and universe are FICTIONAL / SYNTHETIC. The review step is recorded
under the name given by --reviewer; nothing is enforced without one.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from fairbench.ingest.documents import parse_text
from fairbench.instances import named_universe
from fairbench.mandates.dsl import approve
from fairbench.mandates.extract import constraints_from_spec, extract_constraints
from fairbench.mandates.formulas import formula_sheet
from fairbench.mandates.regions import applicable_rules, check_mandate, regional_constraints
from fairbench.rules import load_spec

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mandate", type=Path, default=ROOT / "examples" / "mandate_example.txt")
    ap.add_argument("--region", default="EU", choices=["US", "EU"]), ap.add_argument("--k", type=int, default=20)
    ap.add_argument("--n", type=int, default=150), ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--live", action="store_true"), ap.add_argument("--reviewer", default="reference spec (hand-written)")
    ap.add_argument("--promote-soft", action="store_true")
    args = ap.parse_args()

    u = named_universe(args.n, seed=args.seed)
    doc = parse_text(args.mandate.read_text())
    if args.live:
        cons, spec = extract_constraints(doc, u, fund_id="example")
    else:
        spec = load_spec(args.mandate.with_suffix(".rules.json"))
        cons = constraints_from_spec(spec, doc, u, fund_id="example", extraction_method="hand-written spec + quote and number checks")
    approve(cons, reviewer=args.reviewer)
    name = spec.get("fund_name", "")
    rules = applicable_rules(args.region, fund_name=name)
    findings = check_mandate(cons, rules)
    everything = cons + regional_constraints(rules, u, fund_id="example")
    sheet = formula_sheet(everything, u, args.k, fund_name=name, regional_findings=findings, promote_soft=args.promote_soft)
    out = ROOT / "results" / "mandate_formula_sheet.md"
    out.write_text("_SYNTHETIC universe and fictional mandate; generated by scripts/mandate_formula_sheet.py._\n\n" + sheet)
    bad = [c for c in cons if c.status == "unknown"]
    print(f"{len(cons)} rules from the document ({len(bad)} rejected by the quote or number check), "
          f"{len(rules)} regional requirements for {args.region}")
    for f in findings:
        print(f"  {f['verdict']:<20} {f['title']}")
    print(sheet[sheet.index("## What the enforced rules leave"):])
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
